name: Build Android Phira

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r27c
  ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk-r27c

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config
        # 不要在 CI 中无差别删除源码文件的首行（避免破坏 mod/导出）
        # sed -i '1d' prpr/src/lib.rs  # 已移除以避免破坏 prpr crate

    - name: Download static-lib
      uses: suisei-cn/actions-download-file@v1.3.0
      id: download-static-lib
      with:
        url: "https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip"
        target: ./

    - name: Set Up static-lib
      run: |
        unzip -o prpr-avc.zip -d ./

    - name: Install Android SDK Tools
      run: |
        mkdir -p "${ANDROID_HOME}/cmdline-tools"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d "${ANDROID_HOME}/cmdline-tools"
        # 确保 sdkmanager 在 PATH 中
        export PATH="${ANDROID_HOME}/cmdline-tools/cmdline-tools/bin:${PATH}"
        yes | sdkmanager --sdk_root="${ANDROID_HOME}" "platform-tools" "build-tools;33.0.2" "platforms;android-35"

    - name: Install Android NDK
      run: |
        wget -q https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip -O /tmp/android-ndk-r27c.zip
        unzip -q /tmp/android-ndk-r27c.zip -d "${{ github.workspace }}"
        ls -la "${ANDROID_NDK_HOME}" || true

    - name: Install Rust Toolchains
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        target: aarch64-linux-android

    - name: Build for Android (detect crate root + build)
      run: |
        echo "PWD: $(pwd)"
        ls -la

        # detect where Cargo.toml is
        if [ -f Cargo.toml ]; then
          CRATE_DIR="."
        elif [ -f phira/Cargo.toml ]; then
          CRATE_DIR="phira"
        else
          echo "ERROR: Cargo.toml not found in repo root or phira/ subdir."
          exit 1
        fi

        echo "Building crate in: $CRATE_DIR"
        cd "$CRATE_DIR"

        # ensure cargo-ndk installed and available as cargo subcommand
        cargo install cargo-ndk --force

        echo "=== cargo-ndk info ==="
        cargo ndk --version || true
        cargo ndk --help || true

        # ensure rust target present
        rustup target install aarch64-linux-android || true

        # Proper invocation: use cargo ndk (no duplicated 'ndk'), pass platform with --platform
        echo "=== Building with cargo ndk: target=arm64-v8a platform=35 ==="
        cargo ndk -t arm64-v8a --platform 35 build --release --features "phira/chat"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: |
          phira/target/aarch64-linux-android/release/libphira.so
          target/aarch64-linux-android/release/libphira.so
